Vagrant.configure("2") do |config|   
   config.vm.define :servidorUbuntuA do |servidorUbuntuA|
   servidorUbuntuA.vm.box = "bento/ubuntu-20.04"
   servidorUbuntuA.vm.network :private_network, ip: "192.168.100.4"   
   servidorUbuntuA.vm.hostname = "servidorUbuntuA"      
   servidorUbuntuA.vm.provision :shell, path: "Scripts/script.sh"
   servidorUbuntuA.vm.provider "virtualbox" do |v|
		v.memory = 2048
		v.cpus = 2
		end
   end      
end 