Vagrant.configure("2") do |config|   
   config.vm.define :servidorUbuntu2 do |servidorUbuntu2|
   servidorUbuntu2.vm.box = "bento/ubuntu-20.04"
   servidorUbuntu2.vm.network :private_network, ip: "192.168.90.5"   
   servidorUbuntu2.vm.hostname = "servidorUbuntu2"   
   config.vm.provision :shell, path: "script.sh"  
   config.vm.network :forwarded_port, guest: 80, host: 4567 
   end   
end 