Vagrant.configure("2") do |config|   
   config.vm.define :servidorProxy do |servidorProxy|
   servidorProxy.vm.box = "bento/ubuntu-20.04"
   servidorProxy.vm.network :private_network, ip: "192.168.100.10"   
   servidorProxy.vm.hostname = "servidorProxy"         
   servidorProxy.vm.provision :shell, path: "script0.sh"     
   end   
   config.vm.define :servidorWeb1 do |servidorWeb1|
   servidorWeb1.vm.box = "bento/ubuntu-20.04"
   servidorWeb1.vm.network :private_network, ip: "192.168.100.11"   
   servidorWeb1.vm.hostname = "servidorWeb1"   
   servidorWeb1.vm.provision :shell, path: "script.sh"     
   end   
   config.vm.define :servidorWeb2 do |servidorWeb2|
   servidorWeb2.vm.box = "bento/ubuntu-20.04"
   servidorWeb2.vm.network :private_network, ip: "192.168.100.12"   
   servidorWeb2.vm.hostname = "servidorWeb2"   
   servidorWeb2.vm.provision :shell, path: "script.sh"     
   end   
end 