Vagrant.configure("2") do |config|   
   config.vm.define :servidorUbuntuC do |servidorUbuntuC|
   servidorUbuntuC.vm.box = "bento/ubuntu-20.04"
   servidorUbuntuC.vm.network :private_network, ip: "192.168.100.5"   
   servidorUbuntuC.vm.hostname = "machine1"      
   servidorUbuntuC.vm.provision :shell, path: "Scripts/script.sh"
   end      
end 